import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service - Font Generator',
  description: 'Read our terms of service to understand the rules and guidelines for using our font generator tool. Free to use for personal and commercial purposes.',
  alternates: {
    canonical: `${process.env.NEXT_PUBLIC_SITE_URL || 'https://www.fontforsocial.com'}/terms`,
  },
  robots: {
    index: true,
    follow: true,
  },
  openGraph: {
    title: 'Terms of Service - Font Generator',
    description: 'Terms and conditions for using Font Generator.',
    type: 'website',
  },
};

export default function TermsPage() {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: 'Terms of Service',
    description: 'Terms of service for Font Generator',
    url: `${process.env.NEXT_PUBLIC_SITE_URL || 'https://www.fontforsocial.com'}/terms`,
    datePublished: '2025-09-04T00:00:00Z',
    dateModified: new Date().toISOString(),
    author: {
      '@type': 'Person',
      name: 'Deepak Chauhan',
      url: 'https://www.linkedin.com/in/deepakchauhan333/',
      email: 'dc556316@gmail.com',
    },
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <div className="max-w-4xl mx-auto px-4 py-8">
      <h1 className="text-4xl font-bold text-gray-900 mb-6">Terms of Service</h1>
      
      <div className="prose prose-lg max-w-none text-gray-700">
        <p className="text-sm text-gray-500 mb-6">Last Updated: {new Date().toLocaleDateString()}</p>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">1. Acceptance of Terms</h2>
          <p className="leading-relaxed">
            By accessing and using Font Generator ("the Service"), you accept and agree to be bound by the terms and 
            provisions of this agreement. If you do not agree to these terms, please do not use our Service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">2. Description of Service</h2>
          <p className="leading-relaxed mb-4">
            Font Generator is a free online tool that converts regular text into various Unicode font styles. The Service 
            allows users to:
          </p>
          <ul className="list-disc list-inside space-y-2">
            <li>Generate text in multiple font styles</li>
            <li>Copy generated text to clipboard</li>
            <li>Use generated fonts on any platform that supports Unicode</li>
            <li>Access the service from any device with a web browser</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">3. Use License</h2>
          <p className="leading-relaxed mb-4">
            Permission is granted to use the Service for personal and commercial purposes, subject to the following conditions:
          </p>
          <ul className="list-disc list-inside space-y-2">
            <li>You may use generated fonts for any legal purpose</li>
            <li>You may not claim ownership of the Unicode characters or font styles</li>
            <li>You may not attempt to reverse engineer, decompile, or disassemble the Service</li>
            <li>You may not use the Service for any illegal or unauthorized purpose</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">4. User Responsibilities</h2>
          <p className="leading-relaxed mb-4">
            When using our Service, you agree to:
          </p>
          <ul className="list-disc list-inside space-y-2">
            <li>Use the Service in compliance with all applicable laws and regulations</li>
            <li>Not use the Service to generate offensive, harmful, or illegal content</li>
            <li>Not attempt to disrupt or interfere with the Service's operation</li>
            <li>Not use automated systems to access the Service excessively</li>
            <li>Respect the intellectual property rights of others</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">5. Intellectual Property</h2>
          <p className="leading-relaxed mb-4">
            <strong>Service Content:</strong> The Service, including its design, code, and functionality, is owned by 
            Font Generator and protected by copyright and other intellectual property laws.
          </p>
          <p className="leading-relaxed mb-4">
            <strong>Generated Fonts:</strong> The Unicode characters and font styles generated by our Service are part 
            of the Unicode standard and are not owned by us. You are free to use them as you wish.
          </p>
          <p className="leading-relaxed">
            <strong>User Content:</strong> You retain all rights to the text you input into the Service. We do not claim 
            any ownership of your content.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">6. Disclaimer of Warranties</h2>
          <p className="leading-relaxed mb-4">
            The Service is provided "as is" and "as available" without any warranties of any kind, either express or implied, including but not limited to:
          </p>
          <ul className="list-disc list-inside space-y-2">
            <li>Warranties of merchantability or fitness for a particular purpose</li>
            <li>Warranties that the Service will be uninterrupted or error-free</li>
            <li>Warranties regarding the accuracy or reliability of generated fonts</li>
            <li>Warranties that the Service will meet your specific requirements</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">7. Limitation of Liability</h2>
          <p className="leading-relaxed">
            To the maximum extent permitted by law, Font Generator shall not be liable for any indirect, incidental, 
            special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly 
            or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from:
          </p>
          <ul className="list-disc list-inside space-y-2 mt-4">
            <li>Your use or inability to use the Service</li>
            <li>Any unauthorized access to or use of our servers</li>
            <li>Any interruption or cessation of the Service</li>
            <li>Any bugs, viruses, or other harmful code</li>
            <li>Any errors or omissions in any content</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">8. Platform Compatibility</h2>
          <p className="leading-relaxed">
            While we strive to ensure that generated fonts work across all platforms, we cannot guarantee compatibility 
            with every website, app, or device. Some platforms may not support certain Unicode characters. We are not 
            responsible for how third-party platforms display or handle the generated fonts.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">9. Service Modifications</h2>
          <p className="leading-relaxed">
            We reserve the right to:
          </p>
          <ul className="list-disc list-inside space-y-2 mt-4">
            <li>Modify or discontinue the Service at any time without notice</li>
            <li>Change these Terms of Service at any time</li>
            <li>Refuse service to anyone for any reason</li>
            <li>Add or remove features from the Service</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">10. Third-Party Links</h2>
          <p className="leading-relaxed">
            Our Service may contain links to third-party websites or services. We are not responsible for the content, 
            privacy policies, or practices of any third-party sites. You acknowledge and agree that we shall not be 
            liable for any damage or loss caused by your use of any third-party content or services.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">11. Termination</h2>
          <p className="leading-relaxed">
            We may terminate or suspend your access to the Service immediately, without prior notice or liability, for 
            any reason, including if you breach these Terms. Upon termination, your right to use the Service will 
            immediately cease.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">12. Governing Law</h2>
          <p className="leading-relaxed">
            These Terms shall be governed by and construed in accordance with applicable laws, without regard to its 
            conflict of law provisions. Any disputes arising from these Terms or the Service shall be resolved through 
            binding arbitration or in the courts of competent jurisdiction.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">13. Changes to Terms</h2>
          <p className="leading-relaxed">
            We reserve the right to modify these Terms at any time. We will notify users of any material changes by 
            updating the "Last Updated" date. Your continued use of the Service after such modifications constitutes 
            your acceptance of the updated Terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">14. Contact Information</h2>
          <p className="leading-relaxed">
            If you have any questions about these Terms of Service, please contact us through our website.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">15. Severability</h2>
          <p className="leading-relaxed">
            If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or 
            eliminated to the minimum extent necessary so that these Terms will otherwise remain in full force and effect.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">16. Entire Agreement</h2>
          <p className="leading-relaxed">
            These Terms constitute the entire agreement between you and Font Generator regarding the use of the Service 
            and supersede all prior agreements and understandings.
          </p>
        </section>
      </div>
      </div>
    </>
  );
}
